# Generated by Django 4.0.6 on 2023-01-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_article_date_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Insurance', 'Insurance'), ('Trading', 'Trading'), ('Softwares', 'Softwares')], max_length=100),
        ),
    ]
