# Generated by Django 4.0.6 on 2023-01-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='short_link',
        ),
        migrations.AddField(
            model_name='link',
            name='movie_id',
            field=models.CharField(default=34, max_length=100),
            preserve_default=False,
        ),
    ]
